module;
#include <caudio/ipc/command.hpp>

export module caudio.ipc:command;

export namespace caudio::ipc {
using ::caudio::ipc::Command;
using ::caudio::ipc::ConfigExport;
using ::caudio::ipc::ConfigGet;
using ::caudio::ipc::ConfigImport;
using ::caudio::ipc::ConfigList;
using ::caudio::ipc::ConfigReset;
using ::caudio::ipc::ConfigSet;
using ::caudio::ipc::DeviceList;
using ::caudio::ipc::DeviceSet;
using ::caudio::ipc::DeviceTest;
using ::caudio::ipc::HistoryClear;
using ::caudio::ipc::HistoryList;
using ::caudio::ipc::Info;
using ::caudio::ipc::LibraryAdd;
using ::caudio::ipc::LibraryList;
using ::caudio::ipc::LibraryRemove;
using ::caudio::ipc::LibraryScan;
using ::caudio::ipc::LibrarySearch;
using ::caudio::ipc::LibraryStats;
using ::caudio::ipc::LibraryStatsDetailed;
using ::caudio::ipc::Next;
using ::caudio::ipc::Pause;
using ::caudio::ipc::Play;
using ::caudio::ipc::PlaylistDelete;
using ::caudio::ipc::PlaylistCreate;
using ::caudio::ipc::PlaylistAdd;
using ::caudio::ipc::PlaylistExport;
using ::caudio::ipc::PlaylistImport;
using ::caudio::ipc::PlaylistList;
using ::caudio::ipc::PlaylistLoad;
using ::caudio::ipc::PlaylistRename;
using ::caudio::ipc::PlaylistSave;
using ::caudio::ipc::PlaylistTracks;
using ::caudio::ipc::Prev;
using ::caudio::ipc::Preview;
using ::caudio::ipc::QueueAdd;
using ::caudio::ipc::QueueClear;
using ::caudio::ipc::QueueCreate;
using ::caudio::ipc::QueueDelete;
using ::caudio::ipc::QueueList;
using ::caudio::ipc::QueueMove;
using ::caudio::ipc::QueueQueues;
using ::caudio::ipc::QueueRemove;
using ::caudio::ipc::QueueRepeat;
using ::caudio::ipc::QueueShuffle;
using ::caudio::ipc::QueueSwitch;
using ::caudio::ipc::Restart;
using ::caudio::ipc::Resume;
using ::caudio::ipc::Seek;
using ::caudio::ipc::Shutdown;
using ::caudio::ipc::StatusReq;
using ::caudio::ipc::Stop;
using ::caudio::ipc::TagEdit;
using ::caudio::ipc::TagGet;
using ::caudio::ipc::VolumeSet;
} // namespace caudio::ipc
